FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
COPY conexion.py ./
COPY embeddings.py ./
COPY ia.py ./
COPY bot_telegram.py ./
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000 8010
CMD ["python", "bot_telegram.py"]
